cameras:
- fps: 5
  height: 480
  id: cam_02
  motion:
    contour_area: 200
    enabled: true
    frame_alpha: 0.02
    threshold: 40
  name: 办公室
  roi:
  - - 12.0
    - 6.0
  - - 9.0
    - 711.0
  - - 1257.0
    - 697.0
  - - 1262.0
    - 15.0
  rtsp_url: "rtsp://172.19.1.30:8554/sms/HCPEurl/commonvideobiz_4Dxnr%2BboWz5iI%2Bg%2B8oOENYQLEjfbrirdRK%2BYUx5nReApUTJjRd3lI%2Fb9rBogq%2FiA6zuiyETvt0%2FYjGC0T%2FNLrVqKMMg5z8YFdRsdQbDFtaSNX2pn7VEiFVP5Y%2FMG45TptXi3U9WUb6WakmI%2FKy2GoNzKAPvp0Jz675s2v6qeiwu0FIij59cFireJti8gFbkuYj57JfMBd%2BVmUMAYyn3dHKBgXBmoZOJ6JVmB7ml50ksWPqcGt65QgLvcLmYX315%2BoPnH3eCdh0qiFtHXmYsrX9NetOJzkvaHbiQ%2BBo%2Fc1PU%3D"
  rules:
    alert_types:
    - intrusion
    - tripwire
    - anomaly/dwell
    - anomaly/crowd
    - anomaly/proximity
    - anomaly/fight
    - anomaly/fall
    - presence
    anomaly:
      crowd:
        confirm_frames: 3
        cooldown: 30.0
        enabled: true
        max_count: 2
        radius: 150.0
      dwell:
        confirm_frames: 2
        cooldown: 60.0
        enabled: true
        max_seconds: 10.0
      fall:
        confirm_frames: 2
        cooldown: 30.0
        enabled: true
        min_ratio_change: 0.5
        min_y_drop: 20.0
        ratio_threshold: 1.0
      fight:
        confirm_frames: 3
        cooldown: 30.0
        enabled: true
        min_persons: 2
        min_speed: 60.0
        proximity_radius: 150.0
      proximity:
        confirm_frames: 3
        cooldown: 30.0
        enabled: true
        min_distance: 50.0
      time_period:
        days:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        enabled: false
        end: '23:59'
        start: 00:00
    counting:
      enabled: true
      window_seconds: 60
    intrusion:
      confirm_frames: 5
      cooldown: 30.0
      enabled: true
    tripwire:
      enabled: true
  tripwires: []
  url: rtsp://127.0.0.1:8555/cam_02
  width: 680
- fps: 5
  height: 480
  id: cam01
  motion:
    contour_area: 200
    enabled: true
    frame_alpha: 0.02
    threshold: 40
  name: 停车场入口
  roi:
  - - 18.0
    - 140.0
  - - 73.0
    - 466.0
  - - 502.0
    - 237.0
  - - 506.0
    - 157.0
  - - 227.0
    - 75.0
  rtsp_url: "rtsp://172.19.1.30:8554/sms/HCPEurl/commonvideobiz_4Dxnr%2BboWz5iI%2Bg%2B8oOENYQLEjfbrirdRK%2BYUx5nReCzgUndBTGPd477ejIKDKDOPJzM2S93V36oizUIpiQ99YWmTlkVJudIkdpgR2cciszZAfeDrpq1khSeXsPVWsirdjKubbiL716xv7UaYCbS0t%2BQg0x9Gin3LeBkeL8KSrpHE1smcr4JRdU3KkpscmDUgRIp4z9nlymPRG%2B7yzO%2BoFepLGAwEWv%2FYjPbE7XM5h7so36k5%2Bv0ifOEsR8YHeove%2FurP8da3vufJJeO1N6dGzEU7hiUui6z67Qx2BtAU1U%3D"
  rules:
    alert_types:
    - intrusion
    - tripwire
    - anomaly/dwell
    - anomaly/crowd
    - anomaly/proximity
    - anomaly/fight
    - anomaly/fall
    - presence
    anomaly:
      crowd:
        confirm_frames: 3
        cooldown: 30.0
        enabled: true
        max_count: 3
        radius: 300.0
      dwell:
        confirm_frames: 5
        cooldown: 60.0
        enabled: true
        max_seconds: 120.0
      fall:
        confirm_frames: 2
        cooldown: 30.0
        enabled: true
        min_ratio_change: 0.5
        min_y_drop: 20.0
        ratio_threshold: 1.0
      fight:
        confirm_frames: 3
        cooldown: 30.0
        enabled: true
        min_persons: 2
        min_speed: 60.0
        proximity_radius: 150.0
      proximity:
        confirm_frames: 3
        cooldown: 30.0
        enabled: true
        min_distance: 50.0
      time_period:
        days:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        enabled: false
        end: '23:59'
        start: 00:00
    counting:
      enabled: true
      window_seconds: 60
    intrusion:
      confirm_frames: 2
      cooldown: 5.0
      enabled: true
    tripwire:
      enabled: true
  tripwires:
  - cooldown: 0.5
    direction: right_to_left
    id: tw9380
    name: 线2
    p1:
    - 68.0
    - 472.0
    p2:
    - 557.0
    - 239.0
  url: rtsp://127.0.0.1:8555/cam01
  width: 640
database:
  path: data/warehouse_vision.db
elasticsearch:
  enabled: false
  host: http://localhost:9222
  index_prefix: warehouse-alerts
events:
  draw_bbox: true
  draw_roi: true
  draw_tripwire: true
  output_dir: events
  screenshot: true
model:
  detector_type: roboflow
  analyze_fps: 3
  classes:
  - 0
  - 1
  - 2
  - 3
  - 5
  - 7
  confidence: 0.3
  path: yolo26m.pt
  roboflow:
    model_id: rfdetr-base
    classes:
    - person
    - truck
    - car
  pose:
    confidence: 0.3
    enabled: false
    path: yolo26m-pose.pt
system:
  log_level: INFO
  stats_interval: 60
web:
  host: 0.0.0.0
  port: 8000
