api:
  listen: :1984
log:
  level: info
rtsp:
  listen: :8555
streams:
  cam01: rtsp://172.19.1.30:8554/sms/HCPEurl/commonvideobiz_4Dxnr%2BboWz5iI%2Bg%2B8oOENYQLEjfbrirdRK%2BYUx5nReCzgUndBTGPd477ejIKDKDOPJzM2S93V36oizUIpiQ99YskvJQzCFE4CY3lEfk%2Ba%2BGypS9fIBcIaC2ayV872XiFJmJ6vYpLXN5p%2Bfj%2Fs5zOlJ8s0KfUCcUf0AeoMoSqXt2Fkknnx9wt73gS6icEYD1SSzrm5vrwiHE55MbWGhDQjlJ5PrutT1t8yZ9BMnjQvPDCeiZh%2BfFx1ofxNtXPHt0Oxzvxi5jpjOUIBp5Xwwmam9MxGhUETODY0VY1kK5tNBQ%3D
  cam_02: rtsp://172.19.1.30:8554/sms/HCPEurl/commonvideobiz_4Dxnr%2BboWz5iI%2Bg%2B8oOENYQLEjfbrirdRK%2BYUx5nReApUTJjRd3lI%2Fb9rBogq%2FiA6zuiyETvt0%2FYjGC0T%2FNLrVqKMMg5z8YFdRsdQbDFtaSNX2pn7VEiFVP5Y%2FMG45TptXi3U9WUb6WakmI%2FKy2GoNzKAPvp0Jz675s2v6qeiwu0FIij59cFireJti8gFbkuYj57JfMBd%2BVmUMAYyn3dHKBgXBmoZOJ6JVmB7ml50ksWPqcGt65QgLvcLmYX315%2BoPnH3eCdh0qiFtHXmYsrX9NetOJzkvaHbiQ%2BBo%2Fc1PU%3D
  came03: rtsp://172.19.1.30:8554/sms/HCPEurl/commonvideobiz_4Dxnr%2BboWz5iI%2Bg%2B8oOENYQLEjfbrirdRK%2BYUx5nReBvOWuaEXd8FQci4Ie45fNQTWzsiOdGdkKSnplvpq%2FCZKHG54Tz84eOUyyIL3xb695R5BTLswkeZu1PgblhQ3gpOiAviwrm%2Bm0SW9iAaNAlpQqbYuSbyRVTJj6GR3M8PV2pioMaZ%2FNoQYN9gN0NBYTBSJ%2FNxR5e9CNmt4obx8m%2FMMkoVHx1NwSttvycCv9PkDmdkVYvgGQiQ3mTm4lOp4TH4InVLWYUjw3aIaZqR3rpMQIKjmuGUPZ9m8C3KsvDas4%3D
